# Generated by Django 5.2.4 on 2025-07-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Applicant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("city", models.CharField(max_length=50)),
                ("university", models.CharField(max_length=100)),
                ("major", models.CharField(max_length=100)),
                (
                    "year_of_study",
                    models.CharField(
                        choices=[
                            ("1", "1st Year"),
                            ("2", "2nd Year"),
                            ("3", "3rd Year"),
                            ("4", "4th Year or Higher"),
                            ("Grad", "Graduate"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
