# Generated by Django 5.2.4 on 2025-07-14 23:20

import applicants.models
import applicants.validators
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="cover_letter",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=applicants.models.upload_to_applicant,
                validators=[
                    django.core.validators.FileExtensionValidator(["pdf", "docx"]),
                    applicants.validators.validate_file_size,
                ],
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="cv",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=applicants.models.upload_to_applicant,
                validators=[
                    django.core.validators.FileExtensionValidator(["pdf", "docx"]),
                    applicants.validators.validate_file_size,
                ],
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="motivation",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="applicant",
            name="submitted_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="applicant",
            name="supporting_documents",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=applicants.models.upload_to_applicant,
                validators=[
                    django.core.validators.FileExtensionValidator(["pdf", "docx"]),
                    applicants.validators.validate_file_size,
                ],
            ),
        ),
    ]
